### PR TITLE
update gcc 4.9.3 -> gcc 5.3.0

### PR DESCRIPTION
**Pull request by mobileoverlord**
I have run through the `menuconfig` and verified that it generates a new defconfig with only this line omitted

### CODE REVIEW

**Comment by mobileoverlord** [comment]
While test building `nerves_toolchain_arm_unknown_linux_gnueabihf` for `darwin` I am getting 
```
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    clang: error: unsupported option '-print-multi-os-directory'
[ERROR]    clang: error: no input files
```

**Comment by fhunleth** [comment]
Maybe the Darwin-specific options are wrong now?

**Comment by mobileoverlord** [comment]
This error did not seem to stop it from producing a final toolchain

**Comment by mobileoverlord** [comment]
:shipit:

**Comment by fhunleth** [comment]
With this change, the alix, galileo, and ag150 systems fail to build. I'll work on updating the ag150 (probably rename it as well). I think we should drop support for alix and galileo, though.

**Pull request merged**
