### PR TITLE
Enable Fortran

### PR DESCRIPTION
**Pull request by fhunleth**
Fortran support increases archive size by about 15% (~10 MB) and adds a
shared library.

### CODE REVIEW

**Comment by fhunleth** [comment]
Before we make an official toolchain that includes Fortran, I'd really like a way to remove the libgfortran shared library from firmware images that don't use it. It adds just enough to .fw files (1 MB) that I think we'll see it in firmware update bandwidth costs for one deployment that I'm involved with. We can "blank out" the shared library in our rootfs_overlay, but I'm hoping for a better solution. I'm certainly fine with putting this in "rc builds" until we have something better, though.

**Comment by fhunleth** [comment]
FYI - I refreshed this PR and updated the commit comment. Importantly, there's no size increase to firmware images unless Fortran is explicitly enabled in Buildroot.

**Review by jjcarstens — APPROVED** [review]
LGTM. Though can you still release these when there is path dep?

**Comment by fhunleth** [comment]
No, the path dep will need to be changed back when we make the hex release. The problem is that if you don't switch to path deps, CI will use the old release when building.

**Pull request merged**
